---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/integration

inputs:
  - name: stemcell
  - name: windows-utilities-release

run:
  path: windows-utilities-release/ci/tasks/run-wuts/run

params:
  AZ:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  NETWORK:
  GINKGO_FOCUS:
  GINKGO_NODES: 4
  GINKGO_SKIP:
  GINKGO_TIMEOUT: 2h # Ginkgo v2 default is 1h
  SSH_TUNNEL_IP:
  SSH_TUNNEL_PRIVATE_KEY:
  SSH_TUNNEL_USER:
  VM_EXTENSIONS:
  VM_TYPE:
  WINDOWS_SSH_FIREWALL_RULE_NAME:
  SKIP_CLEANUP:
