resources:
- name: windows-utilities-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows-utilities-release.git
    username: bosh-admin-bot
    password: ((github_public_repo_token))

- name: golang-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

- name: pester
  type: git
  source:
    uri: https://github.com/pester/Pester.git
    tag_filter: 4.*

- name: bosh-shared-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-shared-ci.git

- name: windows-utilities-release-semver
  type: semver
  source:
    bucket: all-bosh-windows
    key: versions/windows-utilities-release
    access_key_id: ((bosh_windows_ci_assume_aws_access_key.username))
    secret_access_key: ((bosh_windows_ci_assume_aws_access_key.password))
    assume_role_arn: ((bosh_windows_ci_assume_aws_access_key.role_arn))
    initial_version: 0.9.0

- name: gcp-2019-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-windows2019-go_agent

- name: aws-2019-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-windows2019-go_agent

- name: azure-2019-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-windows2019-go_agent

- name: bosh-integration-image
  type: registry-image
  source:
    repository: bosh/integration
    username: ((docker.username))
    password: ((docker.password))

- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    days: [ Saturday ]

jobs:

- name: bump-deps
  plan:
    - in_parallel:
        - get: windows-utilities-release
        - get: golang-release
        - get: weekly
          trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      input_mapping:
        input_repo: windows-utilities-release
      output_mapping:
        output_repo: windows-utilities-release
      params:
        SOURCE_PATH: src/windows-utilities-tests
    - task: build-test
      config:
        image_resource:
          type: registry-image
          source:
            repository: bosh/integration
            username: ((docker.username))
            password: ((docker.password))
        inputs:
          - name: windows-utilities-release
        platform: linux
        run:
          path: "windows-utilities-release/src/windows-utilities-tests/bin/build-test.sh"
    - put: windows-utilities-release
      params:
        repository: windows-utilities-release
        rebase: true

- name: test-windows-utilities
  serial: true
  plan:
  - in_parallel:
    - get: pester
    - get: windows-utilities-release
      trigger: true
  - in_parallel:
    - task: check-windows-defender-tests
      file: windows-utilities-release/ci/tasks/test-check-windows-defender/task.yml
      tags: [ windows-nimbus ]
    - task: enable-windows-defender-tests
      file: windows-utilities-release/ci/tasks/test-enable-windows-defender/task.yml
      tags: [ windows-nimbus ]

- name: run-wuts-gcp-2019
  serial: true
  plan:
    - in_parallel:
      - get: windows-utilities-release
        passed: [test-windows-utilities]
        trigger: true
      - get: stemcell
        resource: gcp-2019-stemcell
      - get: bosh-integration-image
    - task: run-wuts
      tags: [ broadcom ]
      file: windows-utilities-release/ci/tasks/run-wuts/task.yml
      image: bosh-integration-image
      params:
        AZ: z1
        BOSH_CA_CERT: ((iaas_directors_labs-gcp-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_labs-gcp-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_labs-gcp-director_bosh_client.password))
        BOSH_ENVIRONMENT: ((iaas_directors_labs-gcp-director_bosh_environment))
        NETWORK: default
        VM_EXTENSIONS: "50GB_ephemeral_disk"
        VM_TYPE: large

- name: run-wuts-aws-2019
  serial: true
  plan:
    - in_parallel:
      - get: windows-utilities-release
        passed: [test-windows-utilities]
        trigger: true
      - get: stemcell
        resource: aws-2019-stemcell
      - get: bosh-integration-image
    - task: run-wuts
      file: windows-utilities-release/ci/tasks/run-wuts/task.yml
      image: bosh-integration-image
      params:
        AZ: z1
        BOSH_CA_CERT: ((iaas_directors_aws-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_aws-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_aws-director_bosh_client.password))
        BOSH_ENVIRONMENT: ((iaas_directors_aws-director_bosh_environment))
        NETWORK: default
        SSH_TUNNEL_IP: ((iaas_directors_aws-director_bosh_jumpbox_ip))
        SSH_TUNNEL_PRIVATE_KEY: ((iaas_directors_aws-director_bosh_jumpbox_ssh.private_key))
        SSH_TUNNEL_USER: ((iaas_directors_aws-director_bosh_jumpbox_username))
        VM_EXTENSIONS: ""
        VM_TYPE: large

- name: run-wuts-azure-2019
  serial: true
  plan:
    - in_parallel:
      - get: windows-utilities-release
        trigger: true
        passed: [test-windows-utilities]
      - get: stemcell
        resource: azure-2019-stemcell
      - get: bosh-integration-image
    - task: run-wuts
      attempts: 3
      file: windows-utilities-release/ci/tasks/run-wuts/task.yml
      image: bosh-integration-image
      params:
        AZ: z1
        BOSH_CA_CERT: ((iaas_directors_azure-director_bosh_ca_cert.ca))
        BOSH_CLIENT: ((iaas_directors_azure-director_bosh_client.username))
        BOSH_CLIENT_SECRET: ((iaas_directors_azure-director_bosh_client.password))
        BOSH_ENVIRONMENT: ((iaas_directors_azure-director_bosh_environment))
        NETWORK: default
        SSH_TUNNEL_IP: ((iaas_directors_azure-director_bosh_jumpbox_ip))
        SSH_TUNNEL_PRIVATE_KEY: ((iaas_directors_azure-director_bosh_jumpbox_ssh.private_key))
        SSH_TUNNEL_USER: ((iaas_directors_azure-director_bosh_jumpbox_username))
        VM_EXTENSIONS: ""
        VM_TYPE: default

- name: release-final
  serial: true
  plan:
  - in_parallel:
    - get: windows-utilities-release
      passed:
        - run-wuts-aws-2019
        - run-wuts-azure-2019
        - run-wuts-gcp-2019
    - get: windows-utilities-release-semver
      params:
        bump: minor
    - get: bosh-shared-ci
    - get: bosh-integration-image
  - task: finalize-release
    file: bosh-shared-ci/tasks/release/create-final-release.yml
    image: bosh-integration-image
    input_mapping:
      release_repo: windows-utilities-release
      version: windows-utilities-release-semver
    params:
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: bots@cloudfoundry.org
      PRIVATE_YML: |
        ---
        blobstore:
          options:
            access_key_id: ((bosh_windows_ci_assume_aws_access_key.username))
            secret_access_key: ((bosh_windows_ci_assume_aws_access_key.password))
            assume_role_arn: ((bosh_windows_ci_assume_aws_access_key.role_arn))
  - put: windows-utilities-release
    params:
      repository: release_repo
      tag: release_metadata/version
  - put: windows-utilities-release-semver
    params:
      file: windows-utilities-release-semver/number
